Rails.application.routes.draw do
  # Authentication routes (generated by Rails authentication)
  resource :session
  resources :passwords, param: :token

  # User registration
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  # Settings
  resource :settings, only: [ :show, :update ]

  # Account deletion
  delete "account", to: "account#destroy", as: :delete_account

  # Dashboard
  root "dashboard#index"
  post "sync", to: "dashboard#sync", as: :sync

  # Calendar
  get "calendar", to: "calendar#index"
  get "calendar/:year/:month(/:day)", to: "calendar#index", as: :calendar_month

  # Trends (Analytics and Data Insights)
  get "trends", to: "trends#index"

  # Analysis (Advanced Analytics)
  get "analysis", to: "analysis#index"

  # Custom Filters
  resources :filters, only: [ :index, :show, :new, :create, :edit, :update, :destroy ]

  # Projects
  resources :projects do
    resources :expenses, controller: "project_expenses" do
      resources :contributions, only: [ :update ], controller: "expense_contributions"
    end
    resources :memberships, only: [ :create, :destroy ], controller: "project_memberships"
  end

  # Transactions (for hypothetical transactions)
  resources :transactions, only: [ :index, :show, :create, :edit, :update, :destroy ] do
    collection do
      get ":year/:month", to: "transactions#index", as: :month
      get :search
    end
  end

  # Recurring transactions
  resources :recurring_transactions, only: [ :index, :show, :create, :edit, :update, :destroy ] do
    member do
      post :toggle_active
    end
  end

  # Health check and PWA routes...
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end
