Rails.application.routes.draw do
  # Authentication routes (generated by Rails authentication)
  resource :session
  resources :passwords, param: :token

  # User registration
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  # Settings
  resource :settings, only: [ :show, :update ]

  # Account management
  resource :account, only: [ :show, :edit, :update, :destroy ], controller: "account"

  # Dashboard
  root "dashboard#index"
  post "sync", to: "dashboard#sync", as: :sync

  # Calendar
  # Custom route pattern for calendar navigation by year/month/day
  # This is acceptable as calendar view is collection-based filtering
  get "calendar", to: "calendar#index"
  get "calendar/:year/:month(/:day)", to: "calendar#index", as: :calendar_month

  # Trends (Analytics and Data Insights)
  get "trends", to: "trends#index"

  # Projects
  resources :projects do
    member do
      get "stats/bars", to: "projects/stats#bars", as: :stats_bars
    end
    # Use shallow: true to avoid deep nesting (projects → expenses → contributions)
    # This creates shallow routes for expenses: index/new/create are nested,
    # show/edit/update/destroy are shallow (no project_id in URL)
    resources :expenses, controller: "project_expenses", shallow: true do
      collection do
        get :templates
      end
      # Contributions are now shallow (no project_id or expense_id in URL for update action)
      resources :contributions, only: [ :update ], controller: "expense_contributions"
    end
    resources :memberships, only: [ :create, :destroy ], controller: "project_memberships"
  end

  # Transactions (for hypothetical transactions)
  resources :transactions, only: [ :index, :show, :create, :edit, :update, :destroy ] do
    collection do
      # Custom collection route for filtering transactions by year/month
      # This is acceptable as it's a filter/collection route
      get ":year/:month", to: "transactions#index", as: :month
      get :search
    end
  end

  # Recurring transactions
  resources :recurring_transactions, only: [ :index, :create, :edit, :update, :destroy ] do
    collection do
      get :suggest_frequency
    end
    member do
      post :toggle_active
    end
  end

  # Recurring categories
  resources :recurring_categories, only: [ :index, :create, :destroy ]

  # Health check and PWA routes...
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end
